### ISSUE TITLE
Add message `name-is-parameter-and-nonlocal`

### ISSUE THREAD

**Issue by mbyrnepr2** [pylint-dev/pylint#6882]
### Current problem

The following produces a SyntaxError:
```python
def tomato(is_tasty: bool = True):
    nonlocal is_tasty
```

```
python example.py
  File "/Users/markbyrne/programming/example.py", line 2
    nonlocal is_tasty
    ^^^^^^^^^^^^^^^^^
SyntaxError: name 'is_tasty' is parameter and nonlocal
```

### Desired solution

Create a new message in Pylint and emit it in this scenario indicating the error.

**Comment by ramonsaraiva** [comment]
I think I can take this one.

**Comment by mbyrnepr2** [comment]
Great thank you@ @ramonsaraiva!
Feel free to ask questions!

**Comment by jacobtylerwalls** [comment]
@ramonsaraiva Thanks for your work so far, we were able to discover pylint-dev/astroid#2213 thanks to you.

@mbyrnepr2 I'm going to suggest closing this issue and linked PR for the same reason as https://github.com/pylint-dev/pylint/pull/8737#issuecomment-1579014464, since we already emit `nonlocal-without-binding`. WDYT?

**Comment by mbyrnepr2** [comment]
Makes sense @jacobtylerwalls. What about creating an issue for [this one](https://github.com/pylint-dev/pylint/pull/7577/files#r989138708)  also? On mobile so can’t investigate that easily now.

**Comment by jacobtylerwalls** [comment]
I think that's down stream of the arguments() fix. See:

https://github.com/pylint-dev/astroid/blob/eabc6435e08c7f01ccf5a3895c0535a3aad178bf/astroid/nodes/node_classes.py#L857-L858
