### ISSUE TITLE
Solution to inference being too slow on a particular code construct that does not involve a new release for pylint to be usable again

### ISSUE THREAD

**Issue by Pierre-Sassoulas** [pylint-dev/pylint#8248]
### Current problem

We can sometime have catastrophic inference failures where astroid takes 10x the time it would normally takes. See #8150. There's no solution to it currently. The obvious way to solve this is to limit recursion in time and depth. On the other hand we don't want to have pylint be unreliable between run because a recursion got too deep and was cut or timeout went above limit. It's still a bug and need to be fixed, but in the meantime an inference fail is vastly preferable to not being able to run pylint at all.

### Desired solution

Add a timeout and recursion limit to inference as well as a ``fatal`` type message when a recursion is cut this way to tell users that the check might be unreliable because of this and to please report the issue.

### Additional context

#8150, but we already had the problem before with pandas or numpy.

**Comment by clavedeluna** [comment]
So implementation would be:  a new fatal message called "inference-failure" indicating to the user results (all pylint results, just a specific message?) are unreliable and please report an issue (same language here as when pylint crashes".

When would that message be emitted:
1. for any message, when we hit [these parameters](https://github.com/PyCQA/pylint/issues/8150#issuecomment-1423218783)?
2. ^ plus some time limit. I'm hesitant to agree on a time limit because that would indeed lead to more inconsistency. At least a count of inference is consistent across runs.

**Comment by jacobtylerwalls** [comment]
#8150 turned out not to be an issue with recursion, where one node took forever to resolve, but rather just a bunch of nodes unnecessarily re-inferred. I'm less sanguine on spending development hours "fighting the last/wrong war", so I'd suggest not doing this. (Better to chip away at https://github.com/pylint-dev/astroid/issues/529 or https://github.com/pylint-dev/astroid/issues/670).

**Comment by Pierre-Sassoulas** [comment]
Fair enough !
