### ISSUE TITLE
Pylint documentation defaults to latest not stable

### ISSUE THREAD

**Issue by avylove** [pylint-dev/pylint#8727]
### Bug description

Going to https://pylint.readthedocs.io will redirect to https://pylint.readthedocs.io/en/latest/ (currently 3.0.0b1), rather than https://pylint.readthedocs.io/en/stable/ (currently 2.17.4). This is [configurable within Read The Docs](https://docs.readthedocs.io/en/stable/user-defined-redirects.html#root-url-redirect-at).

### Expected behavior

While this is a project choice, it probably makes sense to point to stable since pre-release versions could change and the expectation is most users will be on a recent stable release.

**Comment by Pierre-Sassoulas** [comment]
I think it make sense to use stable as the default version now, I changed the setting. We probably took the latest because we had a lot of activity without a lot of release when doing #5953. But now the doc is a lot more stable and having feature not yet released that are documented is a problem with no benefit anymore.
