### ISSUE TITLE
Example of using pylint as a pre-commit hook does not mention use of spelling extra

### ISSUE THREAD

**Issue by ssbarnea** [pylint-dev/pylint#9465]
### Bug description

At this moment there is no documentation on how to install the `spelling` extra when defining the pylint pre-commit hook. Just adding a pyenchant inside `additional_dependencies` does risk installing a version that is not compatible with the runtime requirements from https://github.com/pylint-dev/pylint/blob/main/pyproject.toml#L56

### Command used

```shell
-
```

### Pylint output

```python
-
```

### Expected behavior

-

### Pylint version

```shell
-
```

**Comment by Pierre-Sassoulas** [comment]
In the doc we have a pre-commit installation guide: https://pylint.readthedocs.io/en/latest/user_guide/installation/pre-commit-integration.html#pre-commit-integration, where we suggest to use a local installation (where the install would supposedly be ``pip install pylint[spelling]`` if using pyenchant). I don't like the ``additional_dependencies`` solution because it's duplicating the dependencies between pre-commit config and the default packaging (pre-commit is never going to support editable install afair). We're going to upgrade the pre-commit doc in https://github.com/pylint-dev/pylint/pull/9463, we could detail what to do if you feel it's necessary.
